### ISSUE TITLE
Help! Deployment always failed.

### ISSUE THREAD

**Issue by highcold** [Bitergia/fiware-devguide-app#121]
when I finished the command "docker-compose up -d", all the components started. However I can't visit "http://tourguide", and I use "docker-compose ps" to check state of all components. The result were "cygnus       /docker-entrypoint.sh         Exit 1"   and  "ul20client           /docker- entrypoint.sh--acpi         Exit 1"

**Comment by dmabtrg** [comment]
Hi, could you provide the following information, please?
- version of TourGuide (master, develop, release (e.g. 0.5.1))
- operating system
- output of the `docker-compose logs` command (create a gist/pastebin and put the url here, do not paste the output directly in the issue)

Also, make sure you have the latest images for the version you're using via `docker-compose pull`.

There's a pending PR (#118) that will replace our custom cygnus image with the official image and that should fix the cygnus container exiting.

The problem with ul20client, without seeing the logs is hard to guess.

Thank you.

**Comment by highcold** [comment]
Thank you for your answer in time, and I so sorry for my late reply due to some urgent things  to deal with and bad network environment to update components in China.
Using your method, I have solved the problem related to cygnus, but  another problem still exists.
Here is the information:
- version of TourGuide is **develop**
- OS is **ubuntu 14.04** 
- Although I have fix the hosts, I can't use gist to create a gist in China. Because the log is big(1.8M),  I upload  [screen.log](http://pan.baidu.com/s/1c1Y8mVu). If I find the way to create a gist, I will upload it in time.

Thank you again for your help @dmabtrg .

**Comment by dmabtrg** [comment]
The following is just a guess, but we've seen it before on some systems.

The `ul20client` container uses the acpi subsystem by default.  If the system where your're running the containers does not support it, it will fail.  Modify the `command` directive on the `docker-compose.yml` file for that container from:

```
command: --acpi
```

to:

```
command: --fake --min 0 --max 100 --variance 5
```

This will create a fake sensor instead of trying to use the ones available on the system, with a minimum value of 0, a maximum of 100 and varying +/-5 between each reading at random.

**Comment by highcold** [comment]
Thank you for your answer.
When I modified the docker-compose.yml, the result was still **Exit1**

```
ul20client:
    image: bitergia/ul20-client:latesct
    hostname: ul20client
    container_name: ul20client
    links:
        - orion
        - idas
    command: --fake --min 0 --max 100 -variance 5
    environment:
        - UL20_IOTA_HOST=idas
        - UL20_IOTA_PORT=7896
        - UL20_IOTA_ADMIN_PORT=4041
        - UL20_API_KEY=tourguide-devices
        - UL20_SERVICE_NAME=tourguide
```

I am expected to introduce more about what I am doing. I am doing this tourguide on Virtual Machine with Ubuntu 14.04, and it doesn't feed any sensor to this program nowadays. What I do is following the the tourguide introduction and I can't get guiding from surrounding people or Chinese documents. So I think I may do something wrong in this process and I don't know that.
If it works and we put it in practical projects, I think fiware will popularize to some extent in China.
Thank you for your help. @dmabtrg
