### ISSUE TITLE
Consider providing a mongo image with data for Mac Users

### ISSUE THREAD

**Issue by jmcanterafonseca** [Bitergia/fiware-devguide-app#4]
Unfortunately docker for Mac has not the capability of running mongoDB with an external data volume mapped to a local folder. That means that for Mac OS users we are going to need to provide an alternative Mongo image that includes both Mongo and the data. 

We can reference such an image in the Docker Compose and provide a new target called 'orion-embedded' or a better name that will allow Mac users to overcome the issue with external data.

**Comment by dmabtrg** [comment]
I think that what you want to do can already be achieved with the current data image, as it uses mongo:2.6 as its base image.  Something like this for the mongo container should work:

```
mongodb:
    image: bitergia/fiware-devguide-restaurant-data:20150728
    expose:
        - "27017"
    command: --smallfiles

```

With this configuration, the container does not rely on volumes from other containers and have both mongo and the database files on the same container.  I don't have Mac OS to test this.  Can you try it?
